name: CI

on: 
  push: 
  pull_request:

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-versions:
          - "3.10"
          - "3.11"
    name: Test Job
    runs-on: ${{matrix.os}}  

    steps: 
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-versions}} 

      - name: Install Dependencies
        run: python -m pip install pytest pytest-cov

      - name: Run tests
        run: pytest --cov=main --cov-report=term --cov-report=xml
        
      - name: Convert schema
        run: coverage xml -o coverage_cobertura.xml
        #test comment, trigger change

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage_cobertura.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80'
      
      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
