name: PR Coverage Diff - CI

on: 
  pull_request:

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-versions:
          - "3.11"
    name: Test Job
    runs-on: ${{matrix.os}}  

    steps: 
      - name: Checkout PR branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-versions}} 

      - name: Install Dependencies
        run: python -m pip install pytest pytest-cov coverage-lcov pytest-json-report diff-cover

      #- name: Run tests with coverage
      #  run: pytest --cov=. --cov-report=xml

      - name: Calculate PR coverage
        run: |
          git fetch origin ${{ github.base_ref }}
          diff-cover coverage.xml --compare-branch=origin/${{ github.base_ref }} --fail-under=100 > pr_coverage.txt

      - name: Comment PR
        uses: actions/github-script@v6
        if: always()
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const fs = require('fs')
            const prCoverage = fs.readFileSync('pr_coverage.txt', 'utf8')
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '## PR Code Coverage Report\n\n```\n' + prCoverage + '\n```'
            })

      - name: Check coverage threshold
        run: |
          if grep -q "FAIL" pr_coverage.txt; then
            echo "Coverage threshold not met"
            exit 1
          fi